language: java
jdk:
- openjdk11
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check publish -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew check -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_d28310a4fc95_key -iv $encrypted_d28310a4fc95_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: ORQfKACthJLPg05WHGIL1lAO9cN4Zn3KYDh4ybcd++L+akAL6+CMECmCKFmcEjsGhPvA4W/dICULD4U5Toz0oL0dTz1fCFbGE8Q+ZdBa5Oag2d/ib/vnDis8dSZ6qGBnC06kMkona2yXsO8bKacw6NGVc4U+9ruA4hKH7pGpK8AAhhaelAQshtJ4Mq46/OYeciAxc3857UdFpHgs7cXF/3mU3bG4ZpkZCw5WTyWGMpOGqKKp1NFgjDiXPfVl+PDrtXK1x8GC3o6z/fiL5v/41EJsIaPkXGtYuxa1n1AfC0Nfy75irkGZX5JKthQJeqZUwjP0WQaotgOBK8fLuiK+FxnCw5FMa3V2NGIEP8Rl7cWNYEzfaF6qYhpcrAWLhYdbxMGJev0MNnL/elT4o4om+X3u3cm3sx+H6K3gBP5yZ5v1Evj+eORIpiwWyKfDhKv4r9gfjp2tLf17R3jcL5h+45DvpyCN1ndJ0g3tmmPoe+fo1QAerfcxHe1N1/jBX6fw5taejhZc8vDagPo/JefSAu5AYByr58staZFCSVnIAA4vVCI9p0F0vZqjzdbblGuCsSZB1pIRNKFQFT56aGebUtb+aYy/AegiYS7/ymFN7kRW/FISQudXn/8Iaza5NnOKM3MI6Sg1gB+aSE4hnhW4krPyK5K27vIFLqULSO+I+qQ=
  - secure: iMdp1pOp65SAXY1jvzcK28NLUpAitTSmBzB9Ivx5nHD0s0FHRDXUxL4etfVbYdxwSjTiZhFJDGOAS5BUfx1JYcfj8KgBjHxRJ91R0IP5VBn2B2th6DBy9S3zhalnb/7bypWx1geN4lGX44ggC8F6jfT2kUKwKOEM16fgTeRHYPs/4zpuShhgelcA3ToE/Wk26ItDpIhdRfaZ+bNLHTssjepCKZ9v1vyJYOwx65aHd7ikdwGOx/MaASUgrS5ahVB5la084nABI9Q7PBalXSQUIyDZUhYXo2CzfGWXqtM8Iu7z/FiUY/R0lVRtkiRdVk5qWK69/toZxwFt7MtpDCwUqSfUdwSmudG6L1o7yUNPde5ido51pXKD0cdWHCwhCUHG2Z+dLn7lw5OtL/OYkomXVMf5TEmqSliSkiZfZrvUyLf6mWbTG8yOn5pCqqAIwPVBFwG858J/8Q5c+UTTxMFOwzZ2YvNWHtaxd0SVhjuX0TOfdkCNkDGuGYdSS3pzBpJcWwxr4J/2xk7zlO/ZxS1xihC62nd5GH9YkIBDE0Pqjt3Ie2Qmyxb3R4Y0IA7foUkDWfb9Y6dOAJZ5b74MhtxYS1iq77+GqIkFVm3KE5iXKQ1bZiRefqqgL9FouT9OYuJTYTh91Q01msGfByk0IW/qmeOKLnbSPHrJE0oDsBdmyqg=
  - secure: oQ78nQGFkLUv4nP/CWNxRTEZOf56XQG8EleojkOGLvGP8XLIg2yoGNSaN4Hr1ZmypFQEBSdrUcYdvU1jzZbTunRliRG8SsSR7BD3mcR7XlRN7QsFDVTFl/Ish+kB1SlDR444nAqjCoqM5f/ehjeQf1LMHQ8ibahwm/oFQPXIskojYHqTRyF5L0EDmsbX5gc8kkmfoNPVOVYNsXWGXyPhnv8mmClXH9wxqJafoKDxn0RIx4Z8UzweHX8BeZWSRh/Cq4v3JmnlvPNahq1KpDVbISPl/BxC0B02EwOOJgwA2NC7gbb0hv1heomp1M5Tt5GEhZsEWDuvCYTDey+23V7tyA7vzikLUuyt6ycEm0N1j6Te3yog5/klCRfrI/xSY/qYYDoJLvgl835dZnmNSU2NeTN6f/Ti3k+EboJYUl9NpAgF9zwk7vKHL3OJUzTOKMu38tGGC3i3GhBBjomodPTnwhJmmE5ZiMqXUABqV6lZG9Y8j/MbX+HLw0QtH64109WCdvdWuIVrqRTxyF3uXhjybcO42x/sjqEhrqpyQzr4xMeFDiuWPwATntEtBg8tyCDhoiVZT3T0GAotx8ZyS96dbrH28V8DsUP0/lWsEJkymBoZwBDOXZf3FRgi0kUA5v/bkjgAQ2h0XoEauT959VOyzlBbfDfRIvaCf9oP0NqP9Fo=
  - secure: XYu59DEZI019sJYhuugO/Ku/WMTQFVG8oIvp8v8F2Xy2hSCzbhv9Bg3CSw/A5Ggs7qEX0VPFCK1cfCZOaDxaoNTvXNdC+C8esuiokSMCGYS1xXjKEx3r0xHZvzUcnVZkkq2XfS+1BqePCvi/dVBw/NjvcSJ6R8ZCdDT3Vbb4DuSGcuYX1A+8+9E9kORy4f7LY2B2lJ1dP+gPI+i8Md6eRR0JpqoctqnlrPbwNrxt0w7Vdwv+X+dYBk4RDcN9oP1IJR92vmpnawhrTe/VkHJfle6ISnj9SReLWeUase+Ce4Zt4cCrs3epPQvSNv/B+/AVEUF0lZEeKzJN6az7B2DonjC+2naMbhrYRmrSqEKWZzo2XVWOGrG0Do1y0XlJiLHw4ek9wZIFxmH5wJH6W429gjeFG/O9H0XTnN1hYyW+Mv1r9jqT3iX3gkrUevG+IsX6PyYWQnS9a7NBZmOxZDmdXbh1USv7rcnCRAOrosnoA9DRC0PGrbjd2fPcLDD7oZ+YZSWi6Omy3czosJxgDBqU81K/tuvfc0Uxqe92tL8VYHpmkD/tHt8XYTrV8zgL8Mplgz2LJDmO26FpcoYZe9fmo/uVrjYrVevdwMx0IFExB46I2ISLGdJ0Y9C/uZZ9Oo7R+7MnzmU2NVb51Nnm0F6032jtk5ri8oXCHq+wurbnX2s=
