language: java
jdk:
- openjdk11
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check publish -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew check -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_d28310a4fc95_key -iv $encrypted_d28310a4fc95_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: TcdMWCCU0ZNv95qEp8pcfJlIvqR2n88OdHWBzv7M7SNQU0o25pfnw+LJAO/Oz0NMYMvQTq4oQXZdNdt1t2F/ESF8JI/bjJcZ0aGFNGd0uqNct/gpN3mA/nhV2MymoSA1p/jW//JyftfbE/DyDTGwd0aoYN/Hz9sBPyxs7o7DYZE9cOvyLrtSW+N6N4AxBNSlICJHMlcDMz37x0rbW126FOfxJEko1eaxmlNOQPxb+uaT+jaPWHqgIsIpl/mN11bN8OXwxCTGe1dfwum+Kv/DdhTIQfwOKKK19d96k5qRQCKEet+iNQIZCfdIRBi0RmKFcYwZGd7An1VXcNrqD3VIivqre9wCF/3W/zsBocSY4qaygGkQTtjPzbNegJOjvCscHSqGfwkhFRALO6z8kU8ub1Xirjg0+D1AXNMUQxo3VYPTTyPu/sIGmf1qtipizxNoBi1iW9WyAUDR9MW3jwzptS4k/kKQH7/Mramgr7o39bhI7fmy4EpaXWiukDiNgJD+zDpcTrRZczZ5ogNCyfsOk51GKWsoiZTOC5ijJKGbd+P8GN2udzPqlH/OIoZ++T09jcuIQbTjBDFBTSZfTKcpcB53P6SBiNp+HkxzeQ5AO+DVDzbvOFwVar43OjQqvGGlW7PhCOcJLEbYHIJ7pvXuXX5xe0M9OpkuXKGFrIYJN2U=
  - secure: Lvg+m9AWbxcLBHZVhFXiVncjKeN0EALrelPJ0D1aLNivEkMEYcn9O3Zdm1TmkS0wC0b0LN0WG+76LsKETtAJx/cvRygZ+hpCXFIGetR9nKrIosImRZoT8QAKofVXM7CBwIPqz16oJnPPznQcvFGfyFRtFaZ6TqRXTLKQRVrv0IuVNcBwvyNHd4+ksLg0Lv9UwsEYtggDHjYfxdlgk4Hh9wfHa1Obh9ozjbft2neyiITi1OlTEtyF4jTjKKma9U8hLeX8tcQQFdmEBhXmCLda9lJENBoHEsANdeiTljDhs8appIdpc8psJNHNiGBzzDsMWsSsaYtJ2ukwJlxaToIMVNHFLVfdo/bMA+oCvkNiJ5vi79tcoWgZ6gtm4ww7rGHHwGmqArcQ7kAeBcjIUFPpHIINdc2dd7H7VRir0qbWT+Crm5ISvYxrbWDigJi1u6xvDUFza5Y8hXNXxvaAInhK4ApAL6CxRu1E6mtD5K9XibpaQCe1VMACqhyH/f6MUZKLGyiFxqoCuuPCzGyaUgi/v2v+eOMvWMaBHFRBKuGA2yZpYm7hcUZ+L07gVAP6uevGJCYq0KOmmUXnEKrAUEMSVw62N7zF6jjGgPETal67UTSSW9hv92ptrtOhJhpCi+0hG2DTzbr7Yt57BkC4YLj+IddDeu6Hc5LZk1pMJvnMmNk=
  - secure: Tkw4gLECUCcDpuszLShZHeW0boUz5zBy9AzqykvNSx+hU9voJhUZpl+uwP3jtW/lGTkrZ/nin9SvIa7rG9fkwKjMNZuh602ul5eZNftHHoE7BLhggyho+Qn5/+Ds9lUvhGmVkCPTL6kxhAq2PZ04YMghaaU3O8djOrfhnPEyjwnJwHaLz79kI2IwuVj5M6GB/UNAwBoznIw9WRcWhtRotf0NJus29S+V9PKVZ3rvdRwrTqKcJny/Oa4aDB11s52VDnJB8AFLO8v7AxCwJeRuLJmfppxVeULKPk/snSan4lcbd0hzVKVECGQL4s62grGQT1HC4DtQ7rXBAP84M5P7M8hecrKYqejY/fJrEplKeWf/12EPoraanmMf6dusYplVejfOQoBJh3nNiYxADHcSsMpmve20VdOlyrlxOcUXwD7dV2jgbFDRGnj9NEcK76hKsw6j3Z+bdWIDf9IqoiAIQhU7ofZ4GcVXavAVeMCzpcg9Owq3I9g3Jqxn0EVeD1vfaj5lra9fvbqs6eqo+fKLA4BVrARHYhEl0q3YbfkHSYZlCCZMeALX5scV+qWrXT1EuONPyf4Gw4z+sA1w2vMtUCRquqZyXX59DDxh/6AwBD0Si4N/zcMMUlMuxbgC7eMjM8wPnGgfg0NjwqtMSDOrHy0u6d0rIb70mMS+2GGXPEc=
  - secure: RIoLNaKCVXCEA9zerisaZLbLnmtZZqz/k6pR2yZN1qpHZ2CVepjjZaa4xiJb7ZGedIkdN8o8Zk5Cziow9Cy4v6jOYxqFv2KdSz3DF7205kgYRZRe5Vvstc0KGiJQaXFD5kUEjRuw+6NQFxu3oMjw5ce5MZNdCezooDCd6/xJo5IbpD8RENzL2YLia82AB8s1JP3cjJnDFrff8J7VKWHTvY3WvURLjeyNQIDztLRnAOkwyLnnyb3DaOjIe+cGzsu7x5kwLfbKUG/VbNxZcvh+iE+cNgBonSMfy123zRThBEoHAmMt1T88Z9QKFrMbHfSWvq8a+YdK5ROMZnVXecPVJUDbVNCtFnHAK/HzFd2kWQU0czBK1A31GoSxbFWW8Wtw0txyy5spYsJhDTHpjPk4MXHesllUvvGLYca3j1LVGkiAxKni2QZMpc3S1jA37Ru+/0RjX8W4TSb3ma1P5DHOTiTAa6LFrbPj+VG8/6QR1OFlgtnzO4Vgb7G1+6e1vvbsVXfMbPXFbNlhjxsUL4CXVXMHlHDOMMIJPhd+z+CsjEamViVFtGeq8HRougAr9SL5v0oQLvUx3mdwz21keVlqJpoJH6XkyysBtHzm6mqjRwqncpZ34xBtpIF5OtJiBM+w3uowOSA/2KC+KttbJUqipqM1XT4SSiO319MVNcfmPmQ=
