language: java
jdk:
- openjdk11
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check publish bintrayUpload -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew jar -x test -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_41922466f452_key -iv $encrypted_41922466f452_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: 8buEQ9g/f3vQJjIA7Y7bVFOyTBXoOEW+MpLv3Q4PFZF3TNvfwaOyr1Ndht7HQYGu0cwETvwn+leZTx8iD6mkvwBCegsEGN+Jo4R3qQEVjbVU3GRim2pfksD2PmYRbCw939bc6KEJHfbwmqJu0fYhyP3JdN7mIRvNNbPP5t54FwLvRvkvOnrsr845gMa4TD1mNiNiiu391YCJVImLddqjIoHGNbeWtnNJRNVuOZkXG/9QS9JNxUho3xJCuEAC3SBXslhynuzA0S6PDTHCl1nLqHfhccQad7ehcCgPJaZZ1F/1Aa8O+TLLGHimgS3XyU8gqP5LLzcqROTEzd6gYVDYdHkXeIJKmg62LU14OgMnLDoyNTV4x9plZrjzBbihpr6TOGhuVZDfs/dfuc13/KS4/QPOOeVTXlXI5N5Bp0LIkEDSZzEBkF4Inmau366hoIDkeN1mh8ceIUH82tDaZoced1HejmEvFMK2xF4emJS5phrCy47GXZo6qE5Rj2VD47EtCNgC7qvNG40oz9MBdWvHUZlYZeB37NBX1FS31iRRwFF0Xnokz58CJYFkcD8dqf7z6iUNqfCZCJud9Fx+oBWuMOm/7BKcV8DACybZWGDxILCdqgtFUmydd/abhyQSBItqdRbiKPgxHanHyZ2MZTPn4aPCOuo7LaXFmwLFwFUiAHw=
  - secure: T00fuJMiGbPA+fojxNpvltJ/YDL9kNa4BgDYHYL8yaA1LUXOE+CP5tbM3ZP7mk7CPRDoBe9avyrhxD+APQ+9/dzfeMWMV7Az8mI4IIirjvJqk1NM912SEZWeHZvg8DZCapM5Az0jz0uL5cPyYFbKcfWho02LzfOT+IsTxPIW7L/XmMlY4ZUyRO2oPe4du1f0dbTVlOiTRVozeuPpHTPKTDGyEs8VFTB5utoOwcaUmNpDtPwgrvjLXXcUkk8qun4lX+2tUE3o+ZUwVluQnO38nTYgMgT/qNx+7p0dXz/AOqY1YMYFtbT2W8BOKMF7T1783Jc7AFyqtig3QSY+TegHklhzl7x6bjlqCL/BRRfn9qgm7+flax06N+JWC2mObpfig3DMzLewYpPa1c7AGYh5e6qBxVkMI1iMRfMthzaO70D1WQ4adDjB6EWztkflExuqhDwh/O7XpFXzHpUKqdWi9TsCLZHyIq8APrkpqyhNlLA7/pYND2IvW3jnq3r+UM3rnm8xfJ5f5KC9577Eo3t0N1udqt2EMoBtp/43kE4wXrzDv5SWP1MYLhEuhDTX7I+0rVhO1A1fRb8a4u2JXDPglKkty+bpIcHHu0uFDOjjfAquc7k9THkcZQ4j9SsSWCTa2SwCUhUUw2RQV0QritR7u7+XtuJ5Wi+ewvRx+YmVzA4=
  - secure: TlW7EGQN7I664TYePu/XFDgKc1NuzoaEpAZu8IZjYmhrWz/m0rUsXEkeunuafEZ8M4A4de/Mz/+xrBu1cGa+Zdc5o2Crpc8EYehIHbfW19NPAgcKVHeT747Qoxxg0qHjCbIET3vBeX/KhBoVeeuAoeeDjIS3Z+3+i9QBHFrZbLlLPSCw193bVZUmHP778JD+RHTSi3F609auaYxv4a6BuvUTq8Md+/y8W8sDyo+eNfoQ37RegKjSTAKaVBZ2CUMu7a+NAB0OioC60kdaFQ4GwC/DdOYpvt4FfTjsgO92zujBtzPOp2XFbrstkFDXjt416lDSSXcWs2gmyDj2qaSm4dA2QCxcg9hVn05slBPN2e8YXyBgkJktLG5pNlWlloY8c71HohEF363fNTZvFJ4iZ5CPqbKlJZcpx1sTeecMUIneGOXqTazh39IKH+LKPg6cdSUnf3uyi3EuRCtHXmZeJ6c7vFPcfnrfC29I0KQmXWHZ0bnkxn8F35sKJNzv7x0QQINiGrmYb9J5rV6F5jWkJAxxZjmbdcX+oyPWaGWWt0ZkgRlLmM/84HT46u4T4Y/4B043UCqKDJrLIKAm//4Jc+96p4JVGs1C6bqn9d6ZYLZyWNHZnyy+hNgwgOftmG2QT3ZEcJFx6G3GG0Q2a/EAaMQLg3y2T/e7pS25KWoPxrY=
  - secure: 5s8fsID4NQd6uy3TOPBtvBbHosE92yjptNsKy47X5Vs+GMgXYPopKzyXUMEsyeIdL1z94awYI8nEZuy3BkpSzO5KXMuoAByudyi0p+u0byZS9zdDOORvegmQWIYGif6FKN3LfnDqGKSXaNj5SlFxo0gmLuvUkR9Mnx4BqF5nX0ZjA1ORzpq6udqs/S7ZHFs9hQz2ekcbmDNV7hs/Knj5Zpgtv8Ynkrt+9dGLt33NUVZLJmruIRZV0qCS0WDkc0c1nuMQ5pqxbZDzShoosFcWAFyaxvDFTGlsJZUrMZI5lzS+ZS7FZ8X+1Lc42tBRzsURooabs8kSAA4wdJ6Yx13k4rEk5A7bynaxDPIgiJErmSPVFHSqzp3l6788oN7paQiEFnZFAuJVriMKd+LEH+Zd8bw5+g07KXTAB5DydIVzwnuTnG4zvZxNR0J814lNLAHgOTuHmXT4W/7nya/FUF1BhDWGYH0gUF+pJhWqE1dKK8tm3TzNObDqzNYCvj4AhZLmdarQ2a2m7Qm3UyaHoR87Gb3W9H9dIC1DdI1JdWrPKZQItmDfjXYMMXPBBYEPSAlBot0NSOGAdEtqE5FP1TIoQ5DeWFuZmL3Axkphd0Ey/Oj+KZQ3DF14aOfI+UqLQtTyJ8m9i3W7kskQ6/lS8i0+OQ6YDFzVQpEWLYA4mRyt7cI=
  - secure: 6rmDgJ1MKkkWImc9Gq3LdMYbkUboM/PnGUyZ3dX2tdk4VgztBZ5XDul7ogl0rNZ8bAP4/tU84u9olHF9J4+wMPpH7kp62sNiFkul5JNeCMmy0IsEbhkW2TSIavtxcP8R+2J2GiaE66qgDLvAJjbLSrwJC/rm+Ari7dUfZ6KXt2FoYheI9n7Waato0RoUypgT88iulWC/9+8xnHVjRlw7trziBJ5QrU+dRb4kTcfFuKnfrLEGXUjt1g2nDplK3h0+c7G1qRYrGCPKrzGNF7t5QhJOm3nZqxXJ9DVcG8ei9uwHcNVMN8Me6pPvbwp8Z0ud5N0Ye/QXXZ9AAzdzV8QeP4gAP7YLHhIFq0V5H2O1sne+siInWQ4nvz3KlnZ6+Ow6gc7Z9xqt88O5ei80XeYdkm9O0KmohFSjMj9p8rk5o7X7DJG6kxzn7LNAZYYre7aULqwuWpIZy+Ba8HFsVPmkCLOFKauryiKYAWZJ3uT5Y5J8z0ffTe4AFPWBJvmXda96bDI28sU2XlSkShgvE4ms8Y8DAGNS2LlGfEBpj33ckw+epkxquiWwthRbujVv5Cm+qe4y8rN9yV3SgA7mKZakl27xF/ATLD46wPXKsWagajyXVObkvJxjakmeZcIaUhh3tppMntEdmvVlQQLJtcVbhValqJS5xQdJd4YrXS2geV4=
  - secure: ruX90f6Z193mKtJCnpdqMEcrPQZFFnNLew576pc/YuqNuH+zUiKQtLv6uk8yfbT0Xgw9hXrUVV6+sRBJNAexcN7nePmXfL0PAesmIXri7yNtAQdtNkb0pijUgY0pq5GYm0Vz1aF/cEKfxwWmPhxXBNpdbVc12nfXFiskECZgDMo9OYp4gAeqCAoxGwGH/117b7khoO7oMnf6x7kK7qy3x32SMULJQHB1IhdeHfZv0TlHuXxYXxAIFG/0Yzp2Wbkpoch7UP/JEhAcTsgG2e6L5mBxzRlLimrifMxrKhfpu+hmiJW/AQ65dsZU3fez9GOFB6xTbKn+1/r8A+gKykyUm2SgoCXNWizRfexxQ30vNmkYtVarYYfWett0Ties7n0QmIQwaASzln9chrSRExIWLsRu00qXcKw7kw81cARul7pw/NAojVGdSRhJs+mSk3jihL5ofncPqwtr9+0gJ4zzBKHccuf2KpA8i2UjbOrDRz9f0OpKXntY0gVpK2KUG7W97iDj8CJ4RpE1kVY35DKVO1EIOqd5Xu7eN78OwUCB/bmX4/k44wg6Bq0wveUMh5SqkqaxVS/pDEBlZryVGz/RTpEtCUB9G4hXiXqx8nc0jCD731Ox2Kzo7HN344u5/8na0I7He6FmYwV9jY7uXYwW0LG9m3LEyZ2IbFpqkRuYpVI=
